### ISSUE TITLE
seekpreview frameCount is not enough for long video

### ISSUE THREAD

**Issue by g787543** [boclips/boclips-player#1]
Hello,

I use the video longer then 20 minute, if i set frameCount = 1200(1 sec : 1 pic), the image api will crash. Image loading time will be to long if api does not crash.
But if i set frameCount = 120(10 sec : 1 pic), it may not be accurate.
If my video's time is getting longer, seekpreview accuracy is getting lower.

Have any solution to fix it?

**Comment by antonyoneill** [comment]
Hey @g787543, 

Thank you for your interest in the project! My apologies for not getting back to you sooner, it seems that my notification email was set incorrectly.

The seek preview feature is in its first iteration so we can determine the usefulness of it with the teachers on our platform. This means we've implemented a minimal seek preview, that is not optimised for such a large `frameCount`.

Provided the feedback from the feature is positive I intend to plan further work to achieve a higher frame rate.

Until then I'm afraid the limit is going to be set around 20 frames, I understand this will not provide a one-to-one mapping of frames per second, however I believe this is a good first version of the feature.

Thanks

**Comment by g787543** [comment]
Hello, @antonyoneill 

I fork this project and create one-to-one mapping of frames per second like [this code](https://github.com/g787543/boclips-react-plyr/blob/master/src/MediaPlayer/Plyr/Addons/SeekPreview.ts).
Can you review it?

Thank you.
Best regards.

**Comment by antonyoneill** [comment]
Hi @g787543,

Thank you for looking into resolving this! A pull request is more than welcome, and would be my preferred way of reviewing your code.

I think I get the gist of what you're trying to achieve here, but I think the code could be a little more self explanatory - in particular:
- There are no tests covering any of the functionality that you've implemented here - this is an absolute must, here at Boclips we almost always follow TDD practises.
- The static fields on the SeekPreview `sliceSecond`, `sliceFrameSecond`, `sliceCount` aren't obvious what they're for
- There are several if statements within a loop, you may be able to refactor these into functions, the function name would give the reader more context about what the function is doing.

I'd love to see an updated version of this with some tests in a pull request!

Thanks

**Comment by g787543** [comment]
ok, thank you, i got it.
