### ISSUE TITLE
Support for error handling on the component level

### ISSUE THREAD

**Issue by hemny-singh** [boclips/boclips-player#185]
# Issue
Currently, when the BoCips Player fails to load the video because of some error, it reflects on the UI but I could not find a way to catch the error on the component level where we are loading the BoClips player.

# Why is it important?
It's important to have this feature:
- to track/monitor the errors.
- to show a different fallback on the UI

# Proposed solutions
If we can have a callback function `onError` similar to `onEnd`  which passes the error as a callback argument.
```
const player = PlayerFactory.get(playerContainer);
player.onError((error) => {
  monitorError(error);
});
```

**Comment by rlewan** [comment]
Thanks for reporting this @hemny-singh, we'll look into providing support for this callback 👍

**Comment by arnikaeva** [comment]
@hemny-singh this is added in `6.8.0`, see details in: https://docs.boclips.com/docs/player-guide.html
Let us know if you have any questions!

**Comment by hemny-singh** [comment]
Thank you @arnikaeva @rlewan for resolving it :)
